import re

debug_mode = True
stop_word_pattern = r'\b(?:of|for)\b'

title_match_pattern = re.compile(
    r"(Mr\.\s*|H\.R\.H\.\s*|Mx\.\s*|St\.|Miss\ |Mlle\ |Mine\ |H\.H\.\s*|Ind\.\s*|His\ |Ind\ |Ms\ |Mr\ |Sra\ |Sr\ |M\ |On\ |M\ |Fr\ |H\.O\.\s*|Rev\ |Mme\ |Sr\ |Msgr\ |On\.\s*|Fr\.\s*|Rev\.\s*|H\.E(?:\.\s*(?:Ms\.\s*|Mr\.\s*|Ms\ |Mr\ |Sra\ |Sr\ |Sra\.\s*|Mme|Sr\.\s*|Msgr\.\s*))?|Msgr\.\s*|Mrs\.\s*|Sra\.\s*|Sr\.\s*|Ms\.\s*|Dr\.\s*|Prof\.\s*|M\.\s*|Mme|Ms|S\.E(?:\.\s*(?:Ms\.\s*|Mr\.\s*|Mme|Mr|Ms|Dr|Msgr\.\s*|M\.\s*|Ms\ |Mr\ |Sra\ |Sr\ |M\ |Sra\.\s*|Sr\.\s*))?)")

# predefined list of job titles, department names, Affiliation
profession_names_lemmatized_set = {'arborist',
'forecaster',
'counsellor',
'undersecretary',
'm.p',
'politologue',
'pathologist',
'chaperone',
'coordinator',
'professer',
'asesor',
'dir.',
'capitaine',
'esperto',
'camarógrafo ',
'fotografo',
'photographer',
'subgerente de*',
'consigliere',
'conseillere',
'newswriter',
'dg',
'depute',
'deputé',
'commercante',
'joirnalista',
'bodyguard',
'diplomate',
'eclaireur',
'enseigne',
'vaisseau',
'lady',
'subsecretario',
'vereador',
'conseillère',
'interprète',
'spokesman',
'congresista',
'embajador',
'professuer',
'garde',
'canciller',
'juriste',
'délégué',
'environmentalist',
'mangager',
'dirctor',
'intérprete',
'rector',
'attachée',
'director-general',
'consul-general',
'secretary-general',
'sub-administrator',
'under-secretary',
'sous-directeur',
'sous-directrice',
'under-secretary-general',
'vice-chairperson',
'vice-president',
'vice-chair',
'vice-chairman',
'minister-counsellor',
'editor-in-chief',
'minister-in-charge',
'expert-conseiller',
'vice-président',
'co-chair',
'directeur-pays',
'co-director',
'co-team leader',
'officer-in-charge',
'adviser-deputy',
'deputy-adviser',
'director-at-large',
'deputyminister',
'potter',
'mla',
'congressman',
'protesorero',
'ambassadeur',
'junior',
'superior',
'viceministra',
'ministra',
'pastor',
'responsible',
'coord',
'consul',
'Deputé',
'sergeant',
'cadre',
'maire',
'writer',
'screenwriter',
'serveuse',
'oficial',
'technician',
'driver',
'animatrice',
'videographer',
'membre',
'yasushi',
'stakeholder',
'direzionale',
'chief',
'hr',
'parent',
'acrobat',
'coordonnateur',
'hostess',
'spokeswoman',
'préposée',
'harlequin',
'missionniare',
'investigator',
'financer',
'coordinatrice',
'functionary',
'ministro',
'champion',
'analyste',
'employee',
'point',
'benshi',
'performer',
'lirnyk',
'evaluater',
'miller',
'analyser',
'illustrator',
'ornithologist',
'planner',
'budgeter',
'elder',
'administrator',
'member',
'ceremonial',
'head',
'solicitor',
'presenter',
'maintener',
'porter',
'monologist',
'secretary',
'collaborator',
'legislator',
'coordinador',
'alisa',
'girl',
'anthropologist',
'technologue',
'cameramen',
'attache',
'sousdirection',
'agregado',
'director',
'chairwoman',
'writer',
'candidate',
'technologist',
'captain',
'broker',
'consulgeneral',
'journalist',
'teacher',
'secrétaire',
'archaeologist',
'facilitator',
'jenny',
'photojournalist',
'journalist',
'electrician',
'asesora',
'envoy',
'dealer',
'specialist',
'regulatoryspecialist',
'aquaculturist',
# 'people',
'historian',
'conseillã©',
'focal',
'colloborateur',
'comisionado',
'fundraiser',
'comisario',
'proprietor',
'v.p.',
'serveur',
'copresident',
'adc',
'vp',
'damascener',
'vedette',
'visitor',
'umpire',
'evangelist',
'chef',
'jurist',
'gouverneure',
'governor',
'diplomat',
'partner',
'clerk',
'informaticien',
'comedian',
'ringmaster',
'publisher',
'panelist',
'informar',
'traductrice',
'charge',
'animatør',
'promoter',
'ambassdor',
'chefdebureau',
'chef',
'coordinator',
'gouverneure',
'clerk',
'incharge',
'recteur',
'woman',
'coordinadora',
'curator',
'profesional',
'ministã¨re',
'decorator',
'patrner',
'conservator',
'bartender',
'alumni',
'kobzar',
'chargée',
'chargé',
'jointsecretary',
'navigator',
'designer',
'actress',
'colorist',
'governor',
'secretario',
'marketer',
'politicalscientist',
'politician',
'professional',
'specialiste',
'educator',
'advocacy',
'advocate',
'operator',
'choreographer',
'animator',
'controller',
'documentalist',
'blogger',
'expert',
'vicepdte',
'viceprã©sidente',
'vicepresident',
'counsellor',
'chancellor',
'oceanographer',
'responder',
'statepresident',
'répétiteur',
'activist',
'economist',
'patternmaker',
'maker',
'clown',
'librarian',
'mayor',
'policeman',
'celebrity',
'opã©ratrice',
'barista',
'spouse',
'advisor',
'recruiter',
'student',
'zoologist',
'conseillère',
'ingenieur',
'abogado',
'regulator',
'athlete',
'showgirl',
'actdeputy',
'groundskeeper',
'attaché',
'supervisor',
'vendeur',
'logistician',
'director',
'secrã©tariat',
'ecologist',
'facility',
'child',
'général',
'breeder',
'agent',
'boss',
'viceminister',
'aesthetician',
'gérant',
'messenger',
'entrepreneur',
'lead',
'experte',
'nurse',
'agentderecherche',
'agent',
'collaboratrice',
'lawyer',
'foreman',
'organizer',
'representative',
'advocate',
'dignitary',
'eauxetforãªts',
'controller',
'contingent',
'deputã©',
'aide',
'vice',
'stagehand',
'agente',
'thrower',
'professor',
'flatulist',
'gerente',
'correspondent',
'reverend',
'craftsman',
'guest',
'prã©sident',
'codirector',
'commissioner',
'cofounder',
'beater',
'climateologist',
'innovator',
'undersecretary',
'filmmaker',
'keeper',
'interprã¨te',
'Diplomat',
'job',
'researcher',
'photographe',
'photographer',
'pilot',
'strategist',
'scholar',
'developer',
'steward',
'collaborateur',
'lyricist',
'director',
'aidedecamp',
'senator',
'gardener',
'dã©putã©',
'carpenter',
'rapper',
'viceministro',
'idol',
'person',
'spã©cialiste',
'bricklayer',
'consultant',
'treasurer',
'delegate',
'wheelwright',
'secretary',
'professor',
'ministã©re',
'forester',
'protector',
'climatologist',
'Consellier',
'surveyor',
'artisan',
'crew',
'arbiter',
'prokurist',
'professeur',
'painter',
'woodworker',
'geoscientist',
'attorney',
'superintendent',
'preceptor',
'cinematographer',
'chargé',
'president',
'albaro',
'editor',
'editorinChief',
'sculptor',
'fisherman',
'bãœndnis',
'prime',
'minister',
'controleur',
'asesor',
'programassistant',
'assistant',
'laureat',
'secretray',
'tiktoker',
'blacksmith',
'acreditador',
'jornalista',
'chauffeur',
'avocate',
'chairman',
'chairwoman',
'geographer',
'senateur',
'administrator',
'photographer',
'mjur',
'impressionist',
'philanthropist',
'minstrel',
'musician',
'strategy',
'cobbler',
'enlaceaereo',
'jeweler',
'secretaire',
'councilor',
'deputy',
'patricia',
'contractor',
'meteorologist',
'commentator',
'senior',
'administratrice',
'councillor',
'guide',
'tourist',
'attaché',
'profesor',
'consiller',
'philosopher',
'chief',
'coorodnatrice',
'lieutenant',
'police',
'animateur',
'consultor',
'vpadministration',
'dlapiper',
'prosecutor',
'gestionnaire',
'statistician',
'secretaria',
'signalman',
'scientist',
'experto',
'responsable',
'representante',
'representant',
'encargado',
'contratista',
'titular',
'catédratica',
'delegada',
'coordinamento',
'cosejera',
'ingénieur',
'coresponsable',
'rhapsode',
'personality',
'cochairperson',
'asist.',
'asist',
'pipefitter',
'employã©',
'chair',
'security',
'installer',
'producer',
'supporter',
'Support',
'academician',
'microbiologist',
'officer',
'relationniste',
'waiter',
'receptionist',
'buyer',
'travailleuse',
'penciller',
'psychologist',
'beader',
'artist',
'vicegovernor',
'biotechnologist',
'staff',
'evaluator',
'examiner',
'examinator',
'evaluator',
'examinador',
'feller',
'queen',
'directorgeneral',
'informer',
'informar',
'delegator',
'deputyhead',
'crown',
'vicepresident',
'étudiant',
'auditor',
'enforcement',
'streamer',
'pointsman',
'author',
'procurement',
'interior',
'étudiante',
'waitress',
'directeur',
'hairstylist',
'administratice',
'majorette',
'softiä‡',
'cook',
'programmer',
'anchor',
'adaptater',
'porteparole',
'chargã©',
'sãœdwind',
'coach',
'conscjero',
'enseignant',
'maker',
'major',
'pathfinder',
'repairer',
'manager',
'innovator',
'seismologist',
'dirccteur',
'host',
'presidenta',
'convenor',
'conveyor',
'male',
'pharmacist',
'scop',
'judge',
'directora',
'referee',
'tã©cnico',
'plumber',
'auditer',
'manager',
'moldmaker',
'boilermaker',
'adviser',
'headofpress',
'scout',
'reprã©sentante',
'adjointe',
'copresidente',
'correspondent',
'boy',
'host/hostess',
'hostess',
'host',
'biologist',
'man',
'moderator',
'composer',
'principal',
'attachã©',
'counsel',
'clerck',
'clerk',
'président',
'barker',
'consejera',
'spoke',
'lecturer',
'princess',
'miniser',
'communicator',
'nuncio',
'skomorokh',
'hydrologist',
'farrier',
'doctorante',
'illusionist',
'productor',
'merchant',
'chancellor',
'erector',
'leader',
'cop',
'consejero',
'singer',
'servicer',
'chargee',
'assistante',
'physician',
'agronome',
'backstager',
'monitor',
'fundacion',
'translator',
'musician',
'subsecretary',
'critic',
'président',
'dresser',
'relation',
'stagiaire',
'comptroller',
'cochairman',
'diercteur',
'trustee',
'holder',
'viceministre',
'instructor',
'yiseul',
'chairperson',
'ministre',
'conductor',
'premier',
'coo',
'influencer',
'mechanic',
'doctor',
'chercheur',
'educator',
'demographer',
'avocat',
'baker',
'inspector',
'cfo',
'cto',
'cmo',
'securityhead',
'traducteur',
'interpreter',
'negotiator',
'architecte',
'architect',
'codirecteur',
'welder',
'modeller',
'detective',
'master',
'cuisinier',
'producteur',
'chargã©e',
'mentor',
'marquetarian',
'ntnc',
'dancer',
'politician',
'rapporteur',
'camper',
'officier',
'v.p',
'vp',
'counselor',
'chancellor',
'conservationist',
'coordonnatrice',
'conseiller',
'chiefofstaff',
'ScientificResearcher',
'Co-ordinaotor',
'Coordinaotor',
'ordinaotor',
'agronomist',
'observer',
'showrunner',
'archimime',
'editor',
'accountant',
'architect',
'essayist',
'choi',
'intern',
'dispatcher',
'cameraman',
'initiator',
'podcaster',
'directrice',
'coordinator',
'coordinater',
'user',
'diputado',
'adviser',
'advisor',
'technicaladviser',

'viceprésident',
'sapm',
'spammer',
'reader',
'jammer',
'linguist',
'documentaliste',
'financer',
'king',
'enforcer',
'sonidista',
'cambio',
'judge',
'chiefexecutiveofficer',
'member',
'former',
'sawfiler',
'escort',
'mairie',
'caller',
'notator',
'person',
'draftsperson',
'trésorier',
'specialist',
'conservationspecialist',
'preposee',
'convener',
'modeler',
'caissier',
'cashier',
'coordinateur',
'ceo',
'coordenador',
'gunsmith',
'magician',
'naturalist',
'runner',
'jester',
'regalero',
'secrã©taire',
'urbanplanner',
'caméraman',
'hunter',
'chemist',
'epouse',
'tripulacion',
'stundent',
'associate',
'viceprã©sident',
'apprentice',
'sousdirecteur',
'especialista',
'therapist',
'fellow',
'spouse',
'founder',
'camerman',
'itmanager',
'commander',
'ethicist',
'analyst',
'dean',
'practitioner',
'spokesperson',
'showman',
'banker',
'speaker',
'participant',
'loser',
'resident',
'emcee',
'guard',
'visitor',
'chargée',
'asistente',
'mitigator',
'ambassor',
'ambassdor',
'journaliste',
'segundosecretario',
'juridicaladvisor',
'executive',
'beatboxer',
'broadcaster',
'strategist',
'actor',
'phd',
'cisonecc',
'dentist',
'attendant',
'specialist',
'farmer',
'agriculturist',
'securite',
'presidente',
'sociologist',
'mediator',
'rumbo',
'worker',
'ambassador',
'poet',
'officemanager',
'chancellery',
'dj',
'subdirector',
'sommeli',
'bouffon',
'official',
'engineer',
'paleontologist',
'trainee',
'webmestre',
'fisherymanager',
'soaper',
'cochair',
'formerpresident',
'administrateur',
'employee',
'specialenvoy',
'secrétaire',
'adjuster',
'programleader',
'trader',
'actor',
'botanist',
'viceprésident',
'actuary',
'hibi',
'dj',
'youtuber',
'trainer',
'plenipotentiary',
'missionhead',
'jefe',
'servant',
'assistant',
'doyen',
'voluntaria',
'volunteer',
'freelancer',
'geologist',
'forestier',
'ombudsman',
'commissaire',
'campaigner',
'reporter',
'embajador',
'councel',
'mep',
'mp',
'pewterer',
'barrister',
'agregado',
'conseilleur',
'sectionhead',
'economiste',
'geisha',
'publicist',
'salesperson',
'adjoint',
'Attache',
'specialst',
'Attachée',
'cmr',
'etudiant',
'cunsellor',
'realtor',
'student',
'perito',
'pasante',
'advogada',
'advogado',
'empleado',
'abogada',
'ingeniero',
'ingeniera',
'asesora',
'assessor',
'subdirectora',
'funcionario',
'analista',
'ingénleur',
'Attachée',
'commissioner',
'directeur',
'directrice',
'Asesora',
'promotor',
'cousel',
}

# declare the end of the line patterns, in each sentence, they have to be seperated by space.
end_patterns = ["'s", "'re", "'ve", "'ll", "'d", "n't", ",", "-", "aux", "au", "pour", "la", 'du', "de", "al", "van", "-",
                       "da", "du", "del",
                       "las", "los", "van",
                       "al-", "ya", "nee", "née", "bin"]

names_end_join_set = {"de", "al", "van", "-",
                       "de", "da", "du", "del", "la",
                       "las", "los", "van",
                       "al-", "ya", "nee", "née", "bin"}

doubt_cols_abrupt_split_set = {'moreau',
'darwish',
'cruz',
'al-',
'castillo',
'gutierrez',
'ribeiro',
'morales',
'herrera',
'bernard',
'delgado',
'gonzalez',
'rashid',
'ferreira',
'sanchez',
'michel',
'ahmad',
'mostafa',
'garcia',
'abadi',
'laurent',
'mohamede',
'almeida',
'torres',
'robert',
'asghar',
'araujo',
'khalil',
'richard',
'martin',
'fadel',
'karim',
'santos',
'rodriguez',
'amin',
'abdallah',
'ayad',
'correia',
'lopez',
'borges',
'dubois',
'cabral',
'flores',
'teixeira',
'aguilar',
'cardoso',
'dawoud',
'fernandes',
'badawi',
'bilal',
'costa',
'perez',
'hussain',
'gomez',
'ali',
'ibrahim',
'mohamed',
'saleem',
'aziz',
'alvarez',
'abbas',
'ramirez',
'pereira',
'mohammad',
'silva',
'sousa',
'rocha',
'martinez',
'simon',
'ruiz',
'machado',
'bashar',
'ortiz',
'henriques',
'duarte',
'amer',
'nunes',
'reyes',
'durand',
'iglesias',
'oliveira',
'alves',
'habib',
'moreno',
'hadi',
'gervais',
'mohamed',
'mohammed',
'ossman',
'elhaj',
'ahmed',
'taleb',
'mahmoud',
'mcking',
'manuel',
'rodrigues',
'da costa',
'mac donald',
'libanda',
'tjejamba',
'polman',
'ibrahim',
'arosemena',
'barreto',
'acha',
'ayala',
'vargas',
'ríos',
'weiss',
'deustua',
'cárdenas',
'barreto',
'sailele ',
'malielegaoi',
'senadhira',
'nanayakkara',
'kandambi',
'nadeera',
'pallawala',
'sanjaya',
'rathnayake',
'munasinghe',
'ekanayaka',
'mudiyanselage',
'perera',
'jayakody',
'arachchige',
'ahmed',
'elgadi',
'ahmad',
'abbas',
'jarwan',
'cabrera'
}

job_title_allowed_titles_set = {
        "manager", "director", "director general", "head", "president", "ceo", "chairman",
        "directora", "directeur", "officer", "economist", "présidente", "presidente",
        "expert", "advisor", "commissioner"
    }

job_title_negation_set = {
        ", ", "- ", " -", " - ", " of ", " for ", " general ", " to ", " por ", "de ", " del ",
        " a ", " de ", " dus ", " du ", " général ", " Général ", " Ejectivo ", " and ",
        " general ", " ejectivo ", " (", " ( ", " & ", " on ", " en ", " in ", ",", " with ",
        " Support ", " support ", " supporting ", " Supporting ",
        "of ", "for ", "general ", "to ", "por ", "de ", "del ",
        "a ", "de ", "dus ", "du ", "général ", "Général ", " Ejectivo ", " and ",
        "general ", "ejectivo ", "( ", "( ", "& ", "on ", "en ", "in ", ",", "with ",
        "Support ", "support ", "supporting ", "Supporting "
        }

doubt_merge_job_title_set = {"officer", "coordinator", "ambassador", "director", "specialist", "manager", "advisor"}

# if these words are present at the end of the sentence, join the next sentence to this current text
exact_match_words = {" de", " du", " des", " del", " et", "de la", "sur les", " sur", " les",
                " du", "à la", "a la", " al", " et", "et de", "et de la", " y", "y de", "y de la", " el", " le", "provincial",
                "y del", "à", "environmental", "international", "economic", "technical", "governmental",
                "non-governmental", "internacional", "chinese"}

# if these words are present at the end of the sentence, or at the begining of the next sentence join the next sentence to this current text
other_lang_start_stop_words_set = {" de", " du", " des", " del", " et", " la", "de la", "sur les", " sur", " les",
                " du", "à la", "a la", " al", " et", "et de", "et de la", " y", "y de", "y de la", "d'", "-",
                "y del", " en", " el", " le", "provincial", "agencies"}

affiliation_split_data_and_classify = {'ministère de l', 'ministerio de', 'ministère de', 'ministère del', 'ministerio del', 'ministère del', 'ministère des', 'ministry of', 'university of', 'government of', 'senate of', 'parliament of', 'ministry in', 'ministère du'}

strict_affiliation_keywords = {'environment canada', 'federal chancellery', 'foreign affairs canada', "prime minister' s office",
                               "department of energy", "department of treasury", "department of state",
                               'department of foreign affairs and trade', 'department of the environment',
                               'department of the prime minister and cabinet', 'national development and reform commission',
                               'ministère des affaires etrangères et de la coopération ', 'environmental protection agency',
                               'department of agriculture food and the marine', "federal department of foreign affairs",
                               "environment quality authority"}

strict_division_keywords = {'geography',
'communications',
'natural resources & environment',
'ecology and sustainable development',
'admin',
'agricultural markets & productivity',
'climate and sustainable development',
'energy and climate policy',
'climate and forest',
'social work',
'climate law and policy',
'anthropology',
'environment and sustainable development',
'economy',
'policy and research',
'rural development',
'health',
'international cooperation',
'climate diplomacy',
'climate change and energy',
'policy department',
'administration',
'political and business climate',
'international environmental policy',
'climate and energy',
'corporate communications',
'vulnerability',
'legal',
'public affairs',
'affaires etrangères',
'environmental law',
'communication affairs',
'road transport & highways',
'royal protocol',
"presidential press",
"external relations and public information",
"environment and natural resources",
"urban, energy & extractives",
"resource mobilization"}



# somewhere in the code, the data in the set is being removed
minister_of_startswith_ignore_list = {'federal', 'deputy', 'state', 'provincial'}

job_title_startswith_ignore_set = {'federal', 'national'}

multiple_words_affltn_list = [{'peace', 'child'}, {'baker', 'mckenzie'}, {'consulate', 'general'}, {'ministry', 'management'},
                              # {'global', 'environment'},
                              {'global', 'facility'},
                              {"minister' s", "office"},
                              {"minister' s", "office"},
                              # {'minister', 'office'},
                              {'office', 'staff'}]

multiple_words_profession_list = [{'council', 'general'}, {'team', 'leader'},
                                   {'director', 'general'}, {'consul', 'general'},
                                   {'secretary', 'general'}, {'sub', 'administrator'},
                                   {'under', 'secretary'}, {'sous', 'directeur'},
                                   {'sous', 'directrice'}, {'secretary', 'general'},
                                   {'vice', 'chairperson'}, {'vice', 'president'},
                                   {'vice', 'chair'}, {'vice', 'chairman'},
                                   {'minister', 'counsellor'}, {'editor', 'chief'},
                                   {'minister', 'charge'}, {'expert', 'conseiller'},
                                   {'vice', 'président'}, {'co', 'chair'},
                                   {'directeur', 'pays'}, {'co', 'director'},
                                   {'team', 'leader'}, {'officer', 'charge'},
                                   {'adviser', 'deputy'}, {'deputy', 'adviser'},
                                   {'director', 'large'}, {'security', 'coordinator'},
                                   {'géographe', 'amenagiste'}, {'miembro', 'coordinación '},
                                   {'first', 'lady'}, {'honorable', 'deputé'},
                                   {'fonctionnaire', 'finance'}, {'special', 'assistant'},
                                   {'directrice', 'générale'}, {'deputy director'},
                                   {'director general'}, {'senior specialist'},
                                   {'chefe de departamento'}, {'ajudante de campo'},
                                   {'environmental researcher'}, {'deputy head'}, {'senior expert'}]

department_names_set = {
    'group', 'cabinet', 'programas', 'programa', 'service', 'section', 'unidad', 'dirección',
    'bureau', 'department', 'committee', 'team', 'branch',
    'board', 'management', 'system', 'unit', 'division', 'sector',
    'programme', 'panel', 'municipality', 'commitee', 'mairie', 'parishad', 'office', 'campaign', 'faculty',
    'project', 'legales', 'directorate', 'direction', 'autorité', 'fôrets', 'subdireccion', 'sous-direction', 'centre'
}

job_title_new_checklist_words_set = {'director', 'director general', 'head',
                                'president', 'ceo', 'chairman', 'directora',
                                'directeur', 'officer', 'economist', 'manager',
                                'présidente', 'presidente', 'présidente',
                                'expert', 'advisor', 'commissioner'}

affiliation_names_set = {'inc', 'city', 'corporation', 'ltd', 'limited', 'capital',
                         'institute', 'society', 'corp', 'foundation', 'university', 'council', 'association',
                         'authority', 'commission', 'state', 'program', 'organization', 'org', 'com', 'secretariat',
                         'secrétariat', 'ministry', 'center', 'ministerio', 'agency', 'consuladó', 'ministère',
                         'confération', 'délégation', 'sejm', 'corporation', 'xunta', "minister'",
                         'autoridad', 'fédération', 'confédération', 'government', 'parlement', 'agence', 'consulate',
                         'consulado', 'union', 'eeg', 'embassy', 'parliament', 'ambassade', 'mission', 'misión',
                         'initiatives', 'commission', 'gouvernement', 'embajada', "Assembly", "ayuntamiento", "fondation"}

# output columns names, becareful if you change, you have to change the variable in extract_information
# function and also in the color variables excel cell number like 'F', 'K'

output_excel_column_names = ['Group', 'Entity', 'Title', 'Name', 'Name doubt', 'English Translated Job Title',
                             'Job Title',
                             'English Translated Division', 'Division', 'English Translated Affiliation', 'Affiliation',
                             'Extras']

special_chars_set = {'"', '[', ']', '(', ')'}

empty_division_affiliation_vals = {'research', 'technology', 'economicandsocialpolicy', 'legal', 'climateandenergy',
                                   'economics', 'asia,latinamerica', 'government,naturalresources', 'education',
                                   'policyandresearch', 'externalrelations', 'communication', 'climatepolicy',
                                   'lawandsocialpolicy', 'environmentalmarkets', 'renewableenergy',
                                   'internationaldevelopment', 'international', 'forests&climate',
                                   'industrialaffairs', 'economic&socialpolicy', 'policyandcommunication',
                                   'externalaffairs', 'strategiccommunications', 'finance&operations',
                                   'public&industryaffairs', 'publicpolicy', 'climateandforests', 'northamerica',
                                   'climatechange', 'stainability', 'law&socialpolicy', 'research&development',
                                   'political&socialrights', 'conservation', 'internationalaffairs',
                                   'politicalandsocialrights', 'internacional', 'naturalresources', 'climatefinance',
                                   'financeandoperations', 'sustainabledevelopment', 'researchanddevelopment', 'policy',
                                   'agriculture', 'strategicinitiatives', 'africa', 'internationallaw',
                                   'publicandindustryaffairs', 'environment', 'climaterisk', 'socialpolicy',
                                   'environmentalinitiatives', 'climate&forests', 'europe', 'energy', 'carbonfinance',
                                   'internationalpolicyandnegotiations', 'climate&energy', 'climatechangeandenergy',
                                   'policy&research', 'forestsandclimate', 'climatechange&energy', 'governmentalaffairs',
                                   'internationalpolicy&negotiations', 'law'}

# the input data extracted from the PDF.
extracted_input_data = []

# there are some lines, we have to split the words, if they contains, the item in the list.
text_separator_items_set = {'The'}
# docx_file_path = "C:\\Users\\rakes\\Music\\unfccc word files\\2005_COP_11_Montreal_Part_2.docx"
# output_excel_file_path = "C:\\Users\\rakes\\Downloads\\2005_COP_11_Montreal_Part_2_Final11_new2_final.xlsx"

# the pdf, document and excel file names.
file_name = '2005_COP_11_Montreal_Part_1'
docx_file_name = file_name + ".docx"
pdf_file_name = file_name + ".pdf"
excel_file_name = file_name + ".xlsx"

# the path of the input document and the output excel file path
docx_file_path = "C:\\Users\\emuru\\Music\\Music\\A COPS STUFF\\word files\\{}".format(docx_file_name)
output_excel_file_path = "C:\\Users\\emuru\\Music\\Music\\A COPS STUFF\\completed excel files\\{}".format(excel_file_name)
pdf_path = "C:\\Users\\emuru\\Music\\Music\\A COPS STUFF\\pdf files\\{}".format(pdf_file_name)



# ------------------------------------------------------------------------------------------------------------------------------------------
# import re
#
# title_match_pattern = re.compile(
#     r"(Mr\.\s*|H\.R\.H\.\s*|Mx\.\s*|St\.|Mlle|Mine|H\.H\.\s*|Ind\.\s*|His\ |Ind\ |Ms\ |Mr\ |Sra\ |Sr\ |M\ |On\ |M\ |Fr\ |H\.O\.\s*|Rev\ |Mme\ |Sr\ |Msgr\ |On\.\s*|Fr\.\s*|Rev\.\s*|H\.E(?:\.\s*(?:Ms\.\s*|Mr\.\s*|Ms\ |Mr\ |Sra\ |Sr\ |Sra\.\s*|Mme|Sr\.\s*|Msgr\.\s*))?|Msgr\.\s*|Mrs\.\s*|Sra\.\s*|Sr\.\s*|Ms\.\s*|Dr\.\s*|Prof\.\s*|M\.\s*|Mme|Ms|S\.E(?:\.\s*(?:Ms\.\s*|Mr\.\s*|Mme|Mr|Ms|Dr|Msgr\.\s*|M\.\s*|Ms\ |Mr\ |Sra\ |Sr\ |M\ |Sra\.\s*|Sr\.\s*))?)")
#
# data = []
# op = []
# for inner_list in data:
#     is_present = False
#     inner_last_split_idx = 0
#
#     if len(inner_list) > 2:
#         for item_idx, item in enumerate(inner_list[1:]):
#
#             regex = title_match_pattern.search(item)
#             if regex:
#                 is_present = True
#
#                 kk = item.split(regex.group())
#                 first_person_detail = inner_list[inner_last_split_idx:item_idx + 1]
#                 first_person_detail.append(kk[0])
#
#                 rem_person_detail = inner_list[item_idx + 2:]
#                 # rem_person_detail[0] = str(regex.group()) + rem_person_detail[0]
#                 rem_person_detail.insert(0, kk[1])
#                 rem_person_detail[0] = str(regex.group()) + rem_person_detail[0]
#
#                 op.append(first_person_detail)
#                 op.append(rem_person_detail)
#                 inner_last_split_idx = item_idx + 1
#
#             else:
#                 # If no title is found, add to the current list
#                 # new_data[-1].append(item)
#                 pass
#
#     if not is_present:
#         op.append(inner_list)
#
# for k in op:
#     print(k)
# ------------------------------------------------------------------------------------------------------------------------------------------
